# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - 3.1
  - 3.2
  - oldrel
  - release
  - devel

matrix:
  include:
    - os: linux
      dist: precise
      addons:
        apt:
          packages:
            libarchive-dev
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            libarchive-dev
    #- os: osx
      #osx_image: xcode7.3
      #disable_homebrew: true

after_success:
  - Rscript -e 'covr::codecov()'
